#!/bin/sh
# Copyright (C) 2018 Minbari
# Display and control volume with mouse

# Color
color1="#f3f4f5"
color2="#f3f4f5"


# Left click
if [ "${BLOCK_BUTTON}" -eq 1 ]; then
   mixer -S vol +5
# Middle click
elif [ "${BLOCK_BUTTON}" -eq 2 ]; then
   mixer -S vol mute
# Right click
elif [ "${BLOCK_BUTTON}" -eq 3 ]; then
   mixer -S vol -5
fi

Volume=$(mixer vol | cut -c39-42 | tr -d ':')
# Mute=$(mixer pcm >/dev/null 2>&1)
#Mute=$(mixer vol mute >/dev/null)

if [ "${Volume}" -gt 0 ]; then
  echo " ${Volume}%"
  echo " ${Volume}%"
  echo "$color1"
else
  echo "${Volume} "
  echo "${Volume} "
  echo "$color2"
fi   
