#!/bin/sh
# Copyright (C) 2018 Minbari
# Display weather based on http://openweathermap.org/current

API_KEY="your-key"

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

# Color
color="#f3f4f5"

URGENT_LOWER=-5
URGENT_HIGHER=35

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="°C"

WEATHER_URL="https://api.openweathermap.org/data/2.5/weather?id=3860801&appid=2dfc081df4e76038e74923e70f2e8edf&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [ "${WEATHER_MAIN}" = *Snow* ]; then
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo ""
elif [ "${WEATHER_MAIN}" = *Rain* ] || [ "${WEATHER_MAIN}" = *Drizzle* ]; then
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo ""
elif [ "${WEATHER_MAIN}" = *Cloud* ]; then
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo""
elif [ "${WEATHER_MAIN}" = *Clear* ]; then
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo ""
elif [ "${WEATHER_MAIN}" = *Fog* ] || [ "${WEATHER_MAIN}" = *Mist* ]; then
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo ""
else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_CELSIUS}"
  echo "$color"
  echo ""
fi

if [ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ] || [ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]; then
  exit 33
fi
